// Common C1/C2 academic and advanced English vocabulary words
// Sources: Academic Word List (AWL), Oxford C1/C2 lists
const C1_WORDS = new Set([
  'abstract', 'accommodate', 'accomplish', 'accordingly', 'acknowledge',
  'adequate', 'adjacent', 'adverse', 'advocate', 'aggregate',
  'albeit', 'allocation', 'ambiguous', 'amendment', 'analogy',
  'anthropology', 'apparatus', 'appreciable', 'arbitrary', 'aspiration',
  'authentic', 'autonomous', 'beneficial', 'breakthrough', 'bureaucracy',
  'capacity', 'chronic', 'circular', 'cohesion', 'collaborate',
  'command', 'commodity', 'commute', 'compatible', 'compulsory',
  'conceive', 'confidential', 'conform', 'confront', 'conscience',
  'conscious', 'consensus', 'consolidate', 'contemplate', 'controversial',
  'convention', 'convey', 'coordinate', 'correlate', 'criterion',
  'crucial', 'cumulative', 'curriculum', 'debilitate', 'decade',
  'dedicate', 'deduce', 'deficiency', 'demographic', 'denote',
  'depart', 'depict', 'deprive', 'derive', 'desirable',
  'deviate', 'dilemma', 'diminish', 'discipline', 'discourse',
  'discrepancy', 'discrete', 'disposition', 'distinction', 'distinguish',
  'diverge', 'dominant', 'dominate', 'dramatic', 'elaborate',
  'elastic', 'embody', 'emerge', 'empirical', 'encompass',
  'endorse', 'enormous', 'envisage', 'equivalent', 'essence',
  'evaluate', 'evidence', 'evolve', 'exaggerate', 'exceed',
  'excerpt', 'exception', 'exclusive', 'excursion', 'execute',
  'exert', 'exotic', 'expedient', 'expedite', 'explicit',
  'exploit', 'exponent', 'extinguish', 'facilitate', 'feasible',
  'fascinate', 'flourish', 'formidable', 'formulate', 'foster',
  'fragment', 'frequent', 'fundamental', 'further', 'generate',
  'genuine', 'govern', 'harass', 'hierarchy', 'hypothesis',
  'identify', 'illuminate', 'illustrate', 'imaginary', 'imperial',
  'impose', 'impulse', 'incredible', 'independence', 'inherent',
  'inherit', 'innovation', 'inscribe', 'instance', 'institute',
  'instruct', 'insulate', 'integrate', 'integrity', 'intense',
  'interact', 'interest', 'interfere', 'interim', 'intermediate',
  'internal', 'interpret', 'interrupt', 'interval', 'intimidate',
  'intricate', 'intrude', 'intuition', 'invade', 'invest',
  'investigate', 'involve', 'irrelevant', 'iterate', 'judgment',
  'justification', 'legislation', 'legitimate', 'leverage', 'liberal',
  'literal', 'locate', 'machinery', 'manipulate', 'manufacture',
  'marginal', 'mechanism', 'memorize', 'mentor', 'metaphor',
  'methodology', 'microscope', 'minimize', 'miracle', 'miserable',
  'modify', 'monitor', 'motivate', 'multiply', 'mundane',
  'negotiate', 'norm', 'notion', 'notorious', 'obscure',
  'objective', 'obligation', 'observe', 'obsolete', 'obstacle',
  'obtain', 'outbreak', 'outlook', 'overcome', 'override',
  'paradox', 'parallel', 'parliament', 'participant', 'participate',
  'passionate', 'penalty', 'perceive', 'perception', 'permanence',
  'perpetual', 'perspective', 'phenomenon', 'philosophy', 'physically',
  'plausible', 'plea', 'polar', 'pollution', 'postulate',
  'precarious', 'precede', 'prejudice', 'preliminary', 'premise',
  'premium', 'prescribe', 'preserve', 'presume', 'prestige',
  'prevalent', 'pristine', 'proceed', 'proclaim', 'productive',
  'profession', 'profound', 'progression', 'prohibit', 'projection',
  'prominent', 'pronounce', 'propagate', 'proportion', 'proposition',
  'prosperity', 'provoke', 'psychology', 'publicly', 'pursue',
  'qualify', 'radical', 'rational', 'realistic', 'recession',
  'recognize', 'reconcile', 'recreate', 'redundant', 'reflect',
  'reform', 'refrain', 'refuge', 'regime', 'regulate',
  'rehearse', 'relativity', 'reliable', 'reliance', 'relevant',
  'reliable', 'reliance', 'remnant', 'renovate', 'repertoire',
  'repetition', 'replace', 'represent', 'reproduce', 'resemble',
  'reserve', 'resident', 'resign', 'resort', 'resource',
  'respect', 'respond', 'responsibility', 'restore', 'restrain',
  'restrict', 'retail', 'retain', 'retire', 'revenue',
  'reverse', 'review', 'revise', 'revive', 'revolt',
  'revolution', 'rhetoric', 'rhythm', 'rigid', 'rigorous',
  'sacrifice', 'satisfactory', 'scholarship', 'scenario', 'scheme',
  'scientific', 'scrutiny', 'secondary', 'secretary', 'section',
  'sector', 'secure', 'seemingly', 'segment', 'seminar',
  'sensitive', 'sentence', 'separate', 'severe', 'shadow',
  'significant', 'simultaneously', 'skeptical', 'solidarity', 'solution',
  'somewhat', 'specific', 'specify', 'spiritual', 'spontaneous',
  'stabilize', 'standard', 'status', 'statistic', 'stimulus',
  'strategy', 'streamline', 'strictly', 'striking', 'subconscious',
  'subsequent', 'substantial', 'substitute', 'succeed', 'sufficient',
  'suggest', 'suitable', 'summit', 'superficial', 'superior',
  'supplement', 'suppose', 'suppress', 'surrender', 'surrogate',
  'surround', 'survey', 'survive', 'suspect', 'suspend',
  'sustain', 'sympathy', 'systematic', 'tangible', 'technique',
  'terminate', 'thereby', 'thesis', 'tolerance', 'tolerate',
  'totality', 'track', 'tradition', 'transaction', 'transfer',
  'transform', 'translate', 'transmit', 'transparency', 'transpire',
  'traverse', 'tremendous', 'trivial', 'troubled', 'ultimate',
  'unanimous', 'undergo', 'underlie', 'undertake', 'unify',
  'unprecedented', 'unveil', 'urban', 'utilize', 'valid',
  'vanish', 'venturesome', 'verbal', 'verify', 'version',
  'viable', 'vicious', 'vigor', 'vulnerable', 'welfare',
])

const C2_WORDS = new Set([
  'aberration', 'abhor', 'abide', 'abstain', 'abstinent',
  'abstruse', 'accolade', 'acrimony', 'adamant', 'admonish',
  'aesthetic', 'affinity', 'affirm', 'affluent', 'agitate',
  'alacrity', 'altruism', 'amalgamate', 'anachronism', 'anomaly',
  'antagonize', 'antithesis', 'apathy', 'appease', 'archaic',
  'articulate', 'ascertain', 'asperity', 'assiduous', 'atrocity',
  'auburn', 'augment', 'aversion', 'avocation', 'awry',
  'belligerent', 'benevolent', 'bewilder', 'blithe', 'blunder',
  'bolster', 'bolster', 'bombastic', 'brevity', 'brusque',
  'bulwark', 'cacophony', 'candor', 'capricious', 'catharsis',
  'caustic', 'celerity', 'chicanery', 'circumspect', 'cogent',
  'coerce', 'collaborate', 'collude', 'combustion', 'comely',
  'compelling', 'compensate', 'complement', 'compliant', 'comprise',
  'conflagration', 'congenial', 'conjecture', 'connoisseur', 'consanguineous',
  'consonant', 'contagion', 'contemplate', 'contrite', 'contumacious',
  'conundrum', 'copious', 'corroboration', 'courageous', 'cursory',
  'debacle', 'debase', 'debris', 'decadent', 'deception',
  'decipher', 'decimate', 'declaim', 'deference', 'deficiency',
  'deflect', 'deign', 'deliberate', 'delineate', 'delude',
  'demagogue', 'demeanor', 'demented', 'demonstrate', 'denigrate',
  'denounce', 'denouement', 'deplete', 'deplore', 'depraved',
  'deprive', 'derision', 'derivative', 'despicable', 'despondent',
  'detriment', 'devious', 'diatribe', 'dicey', 'didactic',
  'diffident', 'diligent', 'diminutive', 'disingenuous', 'disparate',
  'disparage', 'dissemble', 'disseminate', 'dissolute', 'dissolution',
  'dissuade', 'dogmatic', 'doldrums', 'droll', 'dubious',
  'dulcet', 'efface', 'efficacious', 'effrontery', 'egregious',
  'elaborate', 'ebullient', 'eclectic', 'eclipse', 'efface',
  'effusive', 'elation', 'efface', 'effervesce', 'egalitarian',
  'efficacy', 'egregious', 'elaborate', 'elicit', 'elide',
  'eloquence', 'emaciated', 'embellish', 'embezzle', 'eminence',
  'eminent', 'empathy', 'empirical', 'enervate', 'enigma',
  'enigmatic', 'enmity', 'ennui', 'enrage', 'enrapture',
  'enrich', 'ensconce', 'enthrall', 'entice', 'entrap',
  'enticing', 'entombed', 'ephemeral', 'epicure', 'epitome',
  'equivocal', 'equivocate', 'erratic', 'esoteric', 'espouse',
  'estrange', 'estrangement', 'etch', 'eulogy', 'euphemism',
  'euphoric', 'euphony', 'evanescent', 'evanesce', 'evince',
  'exacerbate', 'exalt', 'exceeding', 'excoriate', 'exculpate',
  'exempt', 'exert', 'exigent', 'exonerate', 'exorbitant',
  'exotic', 'expedient', 'expeditious', 'expel', 'expiate',
  'expiation', 'explicate', 'explicable', 'expound', 'extant',
  'extenuate', 'extol', 'extort', 'extraneous', 'extrapolate',
  'extricate', 'exuberant', 'exult', 'facade', 'facile',
  'fathom', 'fawning', 'fervid', 'fervor', 'fetid',
  'filthy', 'flaunt', 'flippant', 'flourish', 'fluctuate',
  'forbearance', 'foreboding', 'forensic', 'forsake', 'forthright',
  'fortuitous', 'foul', 'fractious', 'fracture', 'fragile',
  'frantic', 'fret', 'frivolous', 'furious', 'furtive',
  'gadfly', 'galvanize', 'garner', 'gaudiness', 'gem',
  'gelid', 'genial', 'germane', 'germinate', 'gesticulate',
  'giddiness', 'glib', 'glum', 'glut', 'gnaw',
  'grandiloquent', 'gregarious', 'grudging', 'grueling', 'guile',
  'gullible', 'habitat', 'hackneyed', 'harangue', 'harrowing',
  'hassle', 'haughty', 'headlong', 'heed', 'hegemony',
  'heinous', 'heresy', 'hermetic', 'hew', 'histrionic',
  'homogeneity', 'hopeless', 'hubris', 'hullabaloo', 'humdrum',
  'hypocrisy', 'hysteric', 'iconoclast', 'idyllic', 'impair',
  'impartial', 'impassive', 'impeccable', 'impeccant', 'impede',
  'impenetrable', 'imperate', 'impetuous', 'implacable', 'implicit',
  'implore', 'impervious', 'impetuous', 'imperial', 'imperialism',
  'impetuous', 'implode', 'implore', 'imply', 'importunate',
  'imposing', 'imprecise', 'imprimatur', 'improbability', 'improvisation',
  'impudent', 'impugn', 'inadvertent', 'inane', 'inarticulate',
  'inborn', 'incandescent', 'incapacitate', 'incapricious', 'incendiary',
  'incense', 'incessant', 'incestuous', 'inch', 'incisive',
  'inclement', 'inclination', 'incoherent', 'incommodious', 'incontinent',
  'incongruous', 'incontestable', 'incontrovertible', 'inconvenient', 'incredulous',
  'inculcate', 'incur', 'indecorous', 'indecorum', 'indelible',
  'indemnity', 'indeterminate', 'indict', 'indignant', 'indignity',
  'indolent', 'indomitable', 'ineffable', 'ineffective', 'ineffectual',
  'ineffable', 'inelegant', 'ineluctable', 'inept', 'inequitable',
  'inestimable', 'inevitability', 'inexorable', 'inexpedient', 'inexplicable',
  'inextricable', 'infallible', 'infamous', 'infatuation', 'infectious',
  'infer', 'inferior', 'infest', 'infidel', 'infiltrate',
  'infirm', 'inflame', 'inflammable', 'inflate', 'inflexible',
  'inflict', 'infatuate', 'infinitude', 'infirmary', 'inflammation',
  'infrastructure', 'infuse', 'ingratiate', 'ingrained', 'inhibit',
  'inhospitable', 'inhuman', 'inhume', 'inimical', 'innate',
  'innocuous', 'innovate', 'inoculate', 'inopportune', 'inordinate',
  'inquisitive', 'insidious', 'insignia', 'insinuate', 'insipid',
  'insolent', 'insomnia', 'insouciant', 'insuperable', 'insuperable',
  'insuperable', 'insuperable', 'insuperable', 'insuperable', 'insuperable',
  'insuperable', 'insuperable', 'insuperable', 'insuperable', 'insuperable',
])

const ALL_ADVANCED = new Set([...C1_WORDS, ...C2_WORDS])

export interface WordLevelInfo {
  word: string
  level: 'C1' | 'C2' | null
  raw: string // original token including punctuation
}

/**
 * Analyze a sentence and return word-level C1/C2 information.
 * Words are matched case-insensitively against a curated C1/C2 vocabulary list.
 */
export function analyzeSentenceLevel(sentence: string): WordLevelInfo[] {
  const tokens = sentence.match(/[\w'-]+|[^a-zA-Z\s]+/g) || []
  return tokens.map(token => {
    const clean = token.replace(/[^a-zA-Z'-]/g, '').toLowerCase()
    if (!clean) return { word: token, level: null, raw: token } as WordLevelInfo
    if (C2_WORDS.has(clean)) return { word: token, level: 'C2' as const, raw: token }
    if (C1_WORDS.has(clean)) return { word: token, level: 'C1' as const, raw: token }
    return { word: token, level: null, raw: token } as WordLevelInfo
  })
}

/**
 * Check if a word is C1 or C2 level (case-insensitive).
 */
export function isAdvancedWord(word: string): boolean {
  return ALL_ADVANCED.has(word.toLowerCase().replace(/[^a-zA-Z'-]/g, ''))
}
