import { create } from 'zustand';
import { persist } from 'zustand/middleware';
export const useSettingsStore = create()(persist((set) => ({
    claudeApiKey: '',
    ollamaUrl: 'http://localhost:11434',
    ollamaModel: 'llama3.2',
    geminiApiKey: '',
    activeProvider: 'claude',
    dailyNewWords: 20,
    bilingualGrammar: true,
    onboardingComplete: false,
    newsApiKey: '733d0d9c99f84bdabd6decaf0525b25a',
    systemTray: true,
    clipboardHotkey: true,
    readingGoalMins: 15,
    theme: 'dark',
    setClaudeApiKey: (claudeApiKey) => set({ claudeApiKey }),
    setOllamaUrl: (ollamaUrl) => set({ ollamaUrl }),
    setOllamaModel: (ollamaModel) => set({ ollamaModel }),
    setGeminiApiKey: (geminiApiKey) => set({ geminiApiKey }),
    setActiveProvider: (activeProvider) => set({ activeProvider }),
    setDailyNewWords: (dailyNewWords) => set({ dailyNewWords }),
    setBilingualGrammar: (bilingualGrammar) => set({ bilingualGrammar }),
    setOnboardingComplete: (onboardingComplete) => set({ onboardingComplete }),
    setNewsApiKey: (newsApiKey) => set({ newsApiKey }),
    setSystemTray: (systemTray) => set({ systemTray }),
    setClipboardHotkey: (clipboardHotkey) => set({ clipboardHotkey }),
    setReadingGoalMins: (readingGoalMins) => set({ readingGoalMins }),
    setTheme: (theme) => set({ theme })
}), { name: 'wiserain-settings' }));
